// <auto-generated />
using System;
using KnowledgeBaseAPI.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeBaseAPI.Data.Migrations.SqlServerMigrations
{
    [DbContext(typeof(KB_DataContext))]
    [Migration("20240423221043_TestMigration01")]
    partial class TestMigration01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:250IdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeBaseAPI.Data.Command", b =>
                {
                    b.Property<Guid>("Descriptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Descriptor");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("KnowledgeBaseAPI.Data.Description", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("KnowledgeBaseAPI.Data.Descriptor", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tech")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("KnowledgeBaseAPI.Data.Documentation", b =>
                {
                    b.Property<Guid>("Descriptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Descriptor");

                    b.ToTable("Documentations");
                });

            modelBuilder.Entity("KnowledgeBaseAPI.Data.Snippet", b =>
                {
                    b.Property<Guid>("Descriptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Descriptor");

                    b.ToTable("Snippets");
                });
#pragma warning restore 612, 618
        }
    }
}
